/*
 * AttributePropertyFrame.java
 *
 * Created on November 23, 2001, 5:48 PM
 */

package fr.esrf.tangoatk.widget.attribute;
import fr.esrf.tangoatk.core.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author  root
 */
public class PropertyFrame extends javax.swing.JFrame {
    IEntity model;
    boolean added = false;
 
    /** Creates new form AttributePropertyFrame */
    public PropertyFrame() {
        initComponents();
	closeButton.setFont(new java.awt.Font("Dialog", 0, 12));
    }

    public void setEditable(boolean b) {
        propertyListViewer1.setEditable(b);
    }
    
    public boolean isEditable() {
	return propertyListViewer1.isEditable();
    }


    public void setModel(IAttribute m) {
	model = m;
	propertyListViewer1.setModel(model.getPropertyMap());
	jTabbedPane2.remove(setPanel);
    }
    
    protected void setViewer(AScalarViewer viewer) {
	// 	GridBagLayout layout =
	// 	    (GridBagLayout)setPanel.getLayout();
	// 	GridBagConstraints c = layout.getConstraints(value);
 	setPanel.remove(value);
 	setPanel.add(viewer); //, c);
	value = viewer;
 	value.setSetter(true);
 	value.setBorder(null);
	value.setAlarmEnabled(false);
 	value.setInfoVisible(false);
 	value.setValueEditable(false);
	value.setValueMaximumLength(5);

    }
    
    public void setModel(IAttributeViewer m) {
	model = m.getModel();
	propertyListViewer1.setModel(model.getPropertyMap());
        trend.setListVisible(false);
	if (m.isValueEditable() && ((IAttribute)model).isWritable()) {

	    if (model instanceof INumberScalar) {
		NumberScalarViewer viewer =
		    new NumberScalarViewer();
		viewer.setModel((INumberScalar)model);
       
                
		setViewer(viewer);
	    } else if (model instanceof IStringScalar) {
		StringScalarViewer viewer = new StringScalarViewer();
		viewer.setModel((IStringScalar)model);
		setViewer(viewer);
	    } // end of else
	    
	} else {
	    jTabbedPane2.remove(setPanel);
	} // end of els
        if (model instanceof INumberScalar) {
            trend.setModel((INumberScalar)model);  
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            closeButton = new javax.swing.JButton();
            jTabbedPane2 = new javax.swing.JTabbedPane();
            jScrollPane1 = new javax.swing.JScrollPane();
            propertyListViewer1 = new fr.esrf.tangoatk.widget.properties.PropertyListViewer2();
            setPanel = new javax.swing.JPanel();
            value = new fr.esrf.tangoatk.widget.attribute.AScalarViewer();
            trend = new fr.esrf.tangoatk.widget.attribute.Trend();
            
            getContentPane().setLayout(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints gridBagConstraints1;
            
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
            
            closeButton.setText("Close");
            closeButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    closeButtonActionPerformed(evt);
                }
            });
            
            closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    closeButtonMouseClicked(evt);
                }
            });
            
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 0;
            gridBagConstraints1.gridy = 1;
            gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 7);
            gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
            getContentPane().add(closeButton, gridBagConstraints1);
            
            jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
            jScrollPane1.setViewportView(propertyListViewer1);
            
            jTabbedPane2.addTab("Properties", jScrollPane1);
          
          value.setBorder(null);
            value.setAlarmEnabled(false);
            value.setInfoVisible(false);
            setPanel.add(value);
            
            jTabbedPane2.addTab("Set Attribute", setPanel);
          
          jTabbedPane2.addTab("trend", trend);
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 0.1;
        gridBagConstraints1.weighty = 0.1;
        getContentPane().add(jTabbedPane2, gridBagConstraints1);
        
        pack();
    }//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        setVisible(false);      // Add your handling code here:
    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
    }

  
    private void addTrendButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
    }

 
    private void trendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
	setVisible(false);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PropertyFrame().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private fr.esrf.tangoatk.widget.properties.PropertyListViewer2 propertyListViewer1;
    private javax.swing.JPanel setPanel;
    private fr.esrf.tangoatk.widget.attribute.AScalarViewer value;
    private fr.esrf.tangoatk.widget.attribute.Trend trend;
    // End of variables declaration//GEN-END:variables

}

