include ../../../../../../../../.make-include

ALL = $(TARGET)/Computer1.class \
      $(TARGET)/Device1.class \
      $(TARGET)/Device2.class \
      $(TARGET)/Device3.class \
      $(TARGET)/NetDevice1.class \
      $(TARGET)/NetDevice2.class \
      $(TARGET)/NetDevice3.class \
      $(TARGET)/Printer1.class \
      $(TARGET)/Printer2.class \
      $(TARGET)/Printer3.class \
      $(TARGET)/Server1.class \
      $(TARGET)/Server2.class \
      $(TARGET)/Storage1.class \
      $(TARGET)/Storage2.class \
      $(TARGET)/Storage3.class \
      $(TARGET)/Storage4.class \
      $(TARGET)/Storage5.class \
      $(TARGET)/XTerm.class

all: utils

jdoc:

utils: $(ALL)
	$(J)
