#!/bin/sh

pwd=`echo $PWD | sed 's/\/segfs\/tango\/tools\/jclient_framework\/ATK\/src\///g'`
echo $pwd
echo  > Makefile
echo 'include ../../../../.makeinclude' >> Makefile
echo 'TARGET=$(JTARGETDIR)/'$pwd >> Makefile
echo '$(TARGET)/%.class: %.java' >> Makefile
echo '	$(JAVAC) -d $(JTARGETDIR) $< ' >> Makefile

echo "" >> Makefile

echo -n 'all: ' >> Makefile

#echo '	$(JAVAC) -d $(JTARGETDIR) *.java' >> Makefile

for f in *.java; do
class=`echo $f | sed s/java$/class/`;
echo -e  '\t$(TARGET)/'$class '\' >> Makefile
done
echo "" >> Makefile
echo 'clean:' >> Makefile
echo '	rm $(TARGET)/*.class 2>/dev/null ' >> Makefile
