include ../../../../../../.make-include


ALL = $(TARGET)/NumberImage.class \
      $(TARGET)/NumberSpectrum.class \
      $(TARGET)/NumberScalar.class \
      $(TARGET)/StringScalar.class \
      $(TARGET)/NumberAttributeHelper.class \
      $(TARGET)/ANumberImageHelper.class \
      $(TARGET)/ANumberSpectrumHelper.class \
      $(TARGET)/ANumberScalarHelper.class \
      $(TARGET)/DoubleScalarHelper.class \
      $(TARGET)/LongScalarHelper.class \
      $(TARGET)/ShortScalarHelper.class \
      $(TARGET)/DoubleSpectrumHelper.class \
      $(TARGET)/LongSpectrumHelper.class \
      $(TARGET)/ShortSpectrumHelper.class \
      $(TARGET)/DoubleImageHelper.class \
      $(TARGET)/LongImageHelper.class \
      $(TARGET)/ShortImageHelper.class \
      $(TARGET)/StringAttributeHelper.class \
      $(TARGET)/AAttribute.class \
      $(TARGET)/InvalidAttribute.class \
      $(TARGET)/AttributeFactory.class \


all: $(ALL)
	$(J)





