package fr.esrf.tangoatk.widget.util.interlock.shape;
/* Class generated by JDraw */

import java.awt.*;

/** ---------- XTerm class ---------- */
public class XTerm {

  private static int[][] xPolys = null;
  private static int[][] yPolys = null;

  private static Color sColor0 = new Color(204,204,204);

  private static int[][] xOrgPolys = {
    {-10,-10,-4,-2,6,8,14,14},
    {-8,-8,12,12},
    {-14,18,18,-14},
    {-18,-17,-15,-14,-14,-15,-17,-18},
    {-5,-3,9,7},
  };

  private static int[][] yOrgPolys = {
    {-16,5,5,7,7,5,5,-16},
    {-14,2,2,-14},
    {9,9,16,16},
    {7,8,8,7,4,2,2,4},
    {-12,-12,0,0},
  };

  static public void paint(Graphics g,Color backColor,int x,int y,double size) {

    // Allocate array once
    if( xPolys == null ) {
      xPolys = new int [xOrgPolys.length][];
      yPolys = new int [yOrgPolys.length][];
      for( int i=0 ; i<xOrgPolys.length ; i++ ) {
        xPolys[i] = new int [xOrgPolys[i].length];
        yPolys[i] = new int [yOrgPolys[i].length];
      }
    }

    // Scale and translate poly
    for( int i=0 ; i<xOrgPolys.length ; i++ ) {
      for( int j=0 ; j<xOrgPolys[i].length ; j++ ) {
        xPolys[i][j] = (int)((double)xOrgPolys[i][j]*size+0.5) + x;
        yPolys[i][j] = (int)((double)yOrgPolys[i][j]*size+0.5) + y;
      }
    }

    // Paint object
    g.setColor(backColor);g.fillPolygon(xPolys[0],yPolys[0],xPolys[0].length);
    g.setColor(Color.black);g.drawPolygon(xPolys[0],yPolys[0],xPolys[0].length);
    g.setColor(sColor0);g.fillPolygon(xPolys[1],yPolys[1],xPolys[1].length);
    g.setColor(Color.black);g.drawPolygon(xPolys[1],yPolys[1],xPolys[1].length);
    g.setColor(Color.black);
    g.drawLine((int)(0.0*size+0.5)+x, (int)(5.0*size+0.5)+y, (int)(4.0*size+0.5)+x, (int)(5.0*size+0.5)+y);
    g.setColor(backColor);g.fillPolygon(xPolys[2],yPolys[2],xPolys[2].length);
    g.setColor(Color.black);g.drawPolygon(xPolys[2],yPolys[2],xPolys[2].length);
    g.setColor(Color.black);
    g.drawLine((int)(-12.0*size+0.5)+x, (int)(11.0*size+0.5)+y, (int)(-11.0*size+0.5)+x, (int)(11.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-12.0*size+0.5)+x, (int)(13.0*size+0.5)+y, (int)(-11.0*size+0.5)+x, (int)(13.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-9.0*size+0.5)+x, (int)(11.0*size+0.5)+y, (int)(-8.0*size+0.5)+x, (int)(11.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-9.0*size+0.5)+x, (int)(13.0*size+0.5)+y, (int)(-8.0*size+0.5)+x, (int)(13.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-6.0*size+0.5)+x, (int)(11.0*size+0.5)+y, (int)(-5.0*size+0.5)+x, (int)(11.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-6.0*size+0.5)+x, (int)(13.0*size+0.5)+y, (int)(-5.0*size+0.5)+x, (int)(13.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(7.0*size+0.5)+x, (int)(12.0*size+0.5)+y, (int)(15.0*size+0.5)+x, (int)(12.0*size+0.5)+y);
    g.setColor(backColor);g.fillPolygon(xPolys[3],yPolys[3],xPolys[3].length);
    g.setColor(Color.black);g.drawPolygon(xPolys[3],yPolys[3],xPolys[3].length);
    g.setColor(Color.black);
    g.drawLine((int)(-17.0*size+0.5)+x, (int)(4.0*size+0.5)+y, (int)(-14.0*size+0.5)+x, (int)(4.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-16.0*size+0.5)+x, (int)(1.0*size+0.5)+y, (int)(-16.0*size+0.5)+x, (int)(0.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-16.0*size+0.5)+x, (int)(0.0*size+0.5)+y, (int)(-14.0*size+0.5)+x, (int)(-4.0*size+0.5)+y);
    g.setColor(Color.black);
    g.drawLine((int)(-14.0*size+0.5)+x, (int)(-4.0*size+0.5)+y, (int)(-10.0*size+0.5)+x, (int)(-5.0*size+0.5)+y);
    g.setColor(Color.black);g.fillPolygon(xPolys[4],yPolys[4],xPolys[4].length);
    g.setColor(Color.black);g.drawPolygon(xPolys[4],yPolys[4],xPolys[4].length);
    g.setColor(Color.black);
    g.drawLine((int)(-5.0*size+0.5)+x, (int)(0.0*size+0.5)+y, (int)(9.0*size+0.5)+x, (int)(-12.0*size+0.5)+y);

  }

  static public void setBoundRect(int x,int y,double size,Rectangle bound) {
    bound.setRect((int)(-18.0*size+0.5)+x,(int)(-16.0*size+0.5)+y,(int)(37.0*size+0.5),(int)(33.0*size+0.5));
  }

}

