include ../../../../../../.make-include

ALL = $(TARGET)/INonAttrNumberSpectrum.class \
      $(TARGET)/INonAttrSpectrumListener.class \
      $(TARGET)/NonAttrNumberSpectrumEvent.class \
      $(TARGET)/NonAttrNumberSpectrum.class \
      $(TARGET)/AttrFunctionSpectrum.class \
      $(TARGET)/AttrDualSpectrum.class \
      $(TARGET)/AttrVectorSpectrum.class \
      $(TARGET)/TimeAndValueDualSpectrum.class \


all: $(ALL)
	$(J)
