include ../../../../../../../.make-include

ALL = $(TARGET)/DataList.class            \
      $(TARGET)/JALabel.class             \
      $(TARGET)/JFontChooser.class        \
      $(TARGET)/JLAxis.class              \
      $(TARGET)/JLChart.class             \
      $(TARGET)/JLChartOption.class       \
      $(TARGET)/JLDataView.class          \
      $(TARGET)/JLDataViewOption.class    \
      $(TARGET)/SearchInfo.class          \
      $(TARGET)/CfFileReader.class        \
      $(TARGET)/OFormat.class             \
      $(TARGET)/IJLChartListener.class    \
      $(TARGET)/JLChartEvent.class        \
      $(TARGET)/IJLChartActionListener.class \
      $(TARGET)/JLChartActionEvent.class

all: utils

utils: $(ALL)
	$(J)

