
# BEANINFO =  ATKNumberFieldBeanInfo.java \

include ../../../../../../.make-include

ALL = $(TARGET)/Node.class                  \
      $(TARGET)/NumberScalarNode.class      \
      $(TARGET)/StringScalarNode.class      \
      $(TARGET)/NumberSpectrumNode.class      \
      $(TARGET)/NumberImageNode.class      \
      $(TARGET)/AttributeNode.class      \
      $(TARGET)/EntityNode.class      \
      $(TARGET)/NodeFactory.class      \
      $(TARGET)/DropTargetListener.class      \
      $(TARGET)/TransferHandler.class      \
      $(TARGET)/IDropHandler.class      \
      $(TARGET)/CommandNode.class      \

all: $(ALL)
	$(J)


