include ../../../../../../.make-include


ALL = $(TARGET)/NumberImage.class \
      $(TARGET)/NumberSpectrum.class \
      $(TARGET)/NumberScalar.class \
      $(TARGET)/StringScalar.class \
      $(TARGET)/NumberAttributeHelper.class \
      $(TARGET)/ANumberImageHelper.class \
      $(TARGET)/ANumberSpectrumHelper.class \
      $(TARGET)/ANumberScalarHelper.class \
      $(TARGET)/DoubleScalarHelper.class \
      $(TARGET)/LongScalarHelper.class \
      $(TARGET)/ShortScalarHelper.class \
      $(TARGET)/UShortScalarHelper.class \
      $(TARGET)/DoubleSpectrumHelper.class \
      $(TARGET)/LongSpectrumHelper.class \
      $(TARGET)/ShortSpectrumHelper.class \
      $(TARGET)/UShortSpectrumHelper.class \
      $(TARGET)/DoubleImageHelper.class \
      $(TARGET)/LongImageHelper.class \
      $(TARGET)/ShortImageHelper.class \
      $(TARGET)/UShortImageHelper.class \
      $(TARGET)/StringAttributeHelper.class \
      $(TARGET)/AAttribute.class \
      $(TARGET)/InvalidAttribute.class \
      $(TARGET)/AttributeFactory.class \
      $(TARGET)/AAttributeHistory.class \
      $(TARGET)/NumberScalarHistory.class \
      $(TARGET)/StringScalarHistory.class \
      $(TARGET)/StringSpectrum.class \
      $(TARGET)/StringSpectrumHelper.class \
      $(TARGET)/NonAttrNumberSpectrum.class \
      $(TARGET)/AttrFunctionSpectrum.class \
      $(TARGET)/AttrDualSpectrum.class \
      $(TARGET)/AttrVectorSpectrum.class \
      $(TARGET)/BooleanImageHelper.class \
      $(TARGET)/BooleanSpectrumHelper.class \
      $(TARGET)/BooleanScalarHelper.class \
      $(TARGET)/BooleanScalar.class \
      $(TARGET)/BooleanSpectrum.class \
      $(TARGET)/BooleanImage.class \
      $(TARGET)/DevStateScalarHelper.class \
      $(TARGET)/DevStateScalar.class \


all: $(ALL)
	$(J)





