include ../../../../../../.make-include



ALL = $(TARGET)/VoidCommandHelper.class    \
      $(TARGET)/ScalarCommandHelper.class  \
      $(TARGET)/ArrayCommandHelper.class   \
      $(TARGET)/TableCommandHelper.class   \
      $(TARGET)/ScalarScalarCommand.class  \
      $(TARGET)/VoidVoidCommand.class      \
      $(TARGET)/InvalidCommand.class       \
      $(TARGET)/ScalarVoidCommand.class    \
      $(TARGET)/BooleanVoidCommand.class    \
      $(TARGET)/StringVoidCommand.class    \
      $(TARGET)/ScalarArrayCommand.class   \
      $(TARGET)/VoidArrayCommand.class     \
      $(TARGET)/TableArrayCommand.class    \
      $(TARGET)/ArrayArrayCommand.class    \
      $(TARGET)/TableScalarCommand.class   \
      $(TARGET)/ArrayScalarCommand.class   \
      $(TARGET)/TableVoidCommand.class     \
      $(TARGET)/ArrayVoidCommand.class     \
      $(TARGET)/VoidScalarCommand.class    \
      $(TARGET)/TableTableCommand.class    \
      $(TARGET)/ArrayTableCommand.class    \
      $(TARGET)/ScalarTableCommand.class   \
      $(TARGET)/VoidTableCommand.class     \
      $(TARGET)/ACommand.class             \
      $(TARGET)/ACommandHelper.class       \
      $(TARGET)/CommandFactory.class       \
      $(TARGET)/VoidVoidCommandGroup.class       \

all: $(ALL)
	$(J)
