include ../../../../../../.make-include


ALL = $(TARGET)/ANumber.class \
      $(TARGET)/NumberImage.class \
      $(TARGET)/NumberSpectrum.class \
      $(TARGET)/NumberScalar.class \
      $(TARGET)/StringScalar.class \
      $(TARGET)/NumberAttributeHelper.class \
      $(TARGET)/ANumberImageHelper.class \
      $(TARGET)/ANumberSpectrumHelper.class \
      $(TARGET)/ANumberScalarHelper.class \
      $(TARGET)/DoubleScalarHelper.class \
      $(TARGET)/LongScalarHelper.class \
      $(TARGET)/ShortScalarHelper.class \
      $(TARGET)/UShortScalarHelper.class \
      $(TARGET)/DoubleSpectrumHelper.class \
      $(TARGET)/LongSpectrumHelper.class \
      $(TARGET)/ShortSpectrumHelper.class \
      $(TARGET)/UShortSpectrumHelper.class \
      $(TARGET)/DoubleImageHelper.class \
      $(TARGET)/LongImageHelper.class \
      $(TARGET)/ShortImageHelper.class \
      $(TARGET)/UShortImageHelper.class \
      $(TARGET)/StringAttributeHelper.class \
      $(TARGET)/AAttribute.class \
      $(TARGET)/InvalidAttribute.class \
      $(TARGET)/AttributeFactory.class \
      $(TARGET)/PolledAttributeFactory.class \
      $(TARGET)/AAttributeHistory.class \
      $(TARGET)/NumberScalarHistory.class \
      $(TARGET)/StringScalarHistory.class \
      $(TARGET)/StringSpectrum.class \
      $(TARGET)/StringSpectrumHelper.class \
      $(TARGET)/BooleanImageHelper.class \
      $(TARGET)/BooleanSpectrumHelper.class \
      $(TARGET)/BooleanScalarHelper.class \
      $(TARGET)/BooleanScalar.class \
      $(TARGET)/BooleanSpectrum.class \
      $(TARGET)/BooleanImage.class \
      $(TARGET)/DevStateScalarHelper.class \
      $(TARGET)/DevStateScalar.class \
      $(TARGET)/UCharScalarHelper.class \
      $(TARGET)/UCharSpectrumHelper.class \
      $(TARGET)/UCharImageHelper.class \
      $(TARGET)/FloatScalarHelper.class \
      $(TARGET)/FloatSpectrumHelper.class \
      $(TARGET)/FloatImageHelper.class \
      $(TARGET)/RawImageHelper.class \
      $(TARGET)/RawImage.class \
      $(TARGET)/EnumScalarHelper.class \
      $(TARGET)/EnumScalar.class \
      $(TARGET)/StringImageHelper.class \
      $(TARGET)/StringImage.class \
      $(TARGET)/DevStateSpectrumHelper.class \
      $(TARGET)/DevStateSpectrum.class \


all: $(ALL)
	$(J)





