/*
 * SingletonStatus.java
 *
 * Created on February 11, 2002, 3:08 PM
 */

package fr.esrf.tangoatk.widget.device;
import fr.esrf.tangoatk.core.Device;
/**
 *
 * @author  root
 */
public class SingletonStatusViewer extends javax.swing.JFrame
    implements IDevicePopUp {

    private static SingletonStatusViewer self;
    StatusViewer statusPanel;
    
    /** Creates new form SingletonStatus */
    private SingletonStatusViewer () {
        initComponents();
    }

    public static SingletonStatusViewer getInstance() {
        if (self == null) {
            self = new SingletonStatusViewer();
        }
        return self;
    }
    
    public void setModel(Device d) {
	if (d == null) return;
	
        deviceStatus.setModel(d);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        deviceStatus = new fr.esrf.tangoatk.widget.device.StatusViewer();
        closeButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        getContentPane().add(deviceStatus, gridBagConstraints1);
        
        closeButton.setText("Close");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.insets = new java.awt.Insets(7, 0, 7, 11);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(closeButton, gridBagConstraints1);
        
        pack();
    }//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // Add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeButtonMouseClicked

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new SingletonStatusViewer().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.esrf.tangoatk.widget.device.StatusViewer deviceStatus;
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables

}
