/*
 * Status.java
 *
 * Created on December 19, 2001, 4:00 PM
 */

package fr.esrf.tangoatk.widget.device;
import fr.esrf.tangoatk.core.Device;
import fr.esrf.tangoatk.core.StatusEvent;
import fr.esrf.tangoatk.core.ErrorEvent;
import fr.esrf.tangoatk.widget.util.UIManagerHelper;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author  root
 */
public class StatusViewer extends javax.swing.JPanel implements fr.esrf.tangoatk.core.IStatusListener {
    Device device;
    /** Creates new form StatusViewer */
    public StatusViewer () {
        initComponents();
	UIManagerHelper.setAll("StatusViewer.TextArea", status);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
          jScrollPane1 = new javax.swing.JScrollPane();
          status = new javax.swing.JTextArea();
          
          setLayout(new java.awt.BorderLayout());
          
          setBorder(new javax.swing.border.TitledBorder("Status"));
          jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
          status.setLineWrap(true);
          status.setEditable(false);
          status.setColumns(50);
          status.setRows(4);
          status.setText("Unknown");
          status.setBackground(new java.awt.Color(204, 204, 204));
          jScrollPane1.setViewportView(status);
          
          add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    public void setModel(Device device) {
	if (this.device != null) 
	    this.device.removeStatusListener(this);
	status.setText("");
        this.device = device;
        device.addStatusListener(this);
	setStatus(device.getStatus());
    }   

	
    public void setRows(int rows) {
        status.setRows(rows);
    }
    
    public int getRows() {
        return status.getRows();
    }
    
    public int getColumns() {
        return status.getColumns();
    }
    
    public void setColumns(int columns) {
        status.setColumns(columns);
    }
    public void setStatus(String s) {
        status.setText(s);
    }

    public void statusChange(StatusEvent evt) {
            setStatus(evt.getStatus());
    }    

    public void errorChange(ErrorEvent evt) {

    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea status;
    // End of variables declaration//GEN-END:variables

}
