include ../../../../../../../../.make-include

ALL = $(TARGET)/ExpressionParser.class           \
      $(TARGET)/ParserHelpDialog.class           \
      $(TARGET)/ParserOptionDialog.class         \
      $(TARGET)/DynamicChartMathExpression.class \
      $(TARGET)/StaticChartMathExpression.class

all: math


math: $(ALL)
	$(J)

