/*
 * BasicErrorHandler.java
 *
 * Created on October 4, 2001, 4:26 PM
 */

package fr.esrf.tangoatk.widget.util;
import fr.esrf.tangoatk.core.*;
import javax.swing.*;
import java.awt.event.*;
public class BasicLogWindow extends JFrame
    implements ILogListener {
    fr.esrf.tangoatk.core.BasicLogAppender model;

    AppenderWindow appender = new AppenderWindow() {
	    protected void debugButtonMouseClicked(MouseEvent evt) {
		debugClicked(evt);
	    }

	    protected void infoButtonMouseClicked(MouseEvent evt) {
		infoClicked(evt);
	    }

	    protected void warningButtonMouseClicked(MouseEvent evt) {
		warningClicked(evt);
	    }
	};

    
    /** Creates new customizer BasicErrorHandler */
    public BasicLogWindow() {
	super();
	setTitle("Log Window");
    }

    public void setModel(fr.esrf.tangoatk.core.BasicLogAppender a) {
	model = a;
	a.setLogListener(this);
    }

    protected void debugClicked(java.awt.event.MouseEvent evt) {
	model.setDebugOutput();
    }

    protected void warningClicked(java.awt.event.MouseEvent evt) {
	model.setWarningOutput();

    }

    protected void infoClicked(java.awt.event.MouseEvent evt) {
	model.setInfoOutput();
    }

    public void close() {
	this.setVisible(false);
    }
    
    public void append(String s) {
	appender.append(s);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        setLayout (new java.awt.BorderLayout ());

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
