/*
 * ButtonBar.java
 *
 * Created on June 19, 2002, 11:22 AM
 */

package fr.esrf.tangoatk.widget.util;

/**
 *
 * @author  root
 */
public class ButtonBar extends javax.swing.JPanel {

    /** Creates new form ButtonBar */


    public ButtonBar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        help = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        help.setFont(new java.awt.Font("Dialog", 0, 12));
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 10, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(help, gridBagConstraints1);
        
        ok.setFont(new java.awt.Font("Dialog", 0, 12));
        ok.setText("OK");
        ok.setSelected(true);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 3;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 2, 10, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        add(ok, gridBagConstraints1);
        
        cancel.setFont(new java.awt.Font("Dialog", 0, 12));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 2;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 10, 2);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTH;
        add(cancel, gridBagConstraints1);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.weightx = 0.1;
        add(jLabel1, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_helpActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed


    boolean cancelVisible = true;
    
    boolean helpVisible = true;
    
    /**
     * Get the value of helpVisible.
     * @return value of helpVisible.
     */
    public boolean isHelpVisible() {
	return helpVisible;
    }
    
    /**
     * Set the value of helpVisible.
     * @param v  Value to assign to helpVisible.
     */
    public void setHelpVisible(boolean  v) {
	if (help == null) return;
	this.helpVisible = v;
	help.setVisible(v);
    }
    
    /**
     * Get the value of cancelVisible.
     * @return value of cancelVisible.
     */
    public boolean isCancelVisible() {
	return cancelVisible;
    }
    
    /**
     * Set the value of cancelVisible.
     * @param v  Value to assign to cancelVisible.
     */
    public void setCancelVisible(boolean  v) {
	if (cancel == null) return;
	this.cancelVisible = v;
	cancel.setVisible(v);
    }

    public javax.swing.JButton getOKButton() {
	return ok;
    }

    public javax.swing.JButton getHelpButton() {
	return help;
    }

    public javax.swing.JButton getCancelButton() {
	return cancel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton help;
    private javax.swing.JButton ok;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
