/*
 * SplashPanel.java
 *
 * Created on March 28, 2002, 12:37 PM
 */

package fr.esrf.tangoatk.widget.util;

/**
 *
 * @author  root
 */
public class SplashPanel extends javax.swing.JPanel {

    /** Creates new form SplashPanel */
    public SplashPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        title = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        setForeground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(298, 245));
        setMinimumSize(new java.awt.Dimension(298, 245));
        setPreferredSize(new java.awt.Dimension(298, 245));
        setOpaque(false);
        title.setFont(new java.awt.Font("Dialog", 1, 18));
        title.setForeground(new java.awt.Color(204, 204, 204));
        title.setText("Title");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(130, 8, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 0.1;
        add(title, gridBagConstraints1);
        
        message.setFont(new java.awt.Font("Dialog", 0, 12));
        message.setForeground(new java.awt.Color(204, 204, 204));
        message.setText("Initializing...");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 8, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 0.1;
        add(message, gridBagConstraints1);
        
        copyright.setFont(new java.awt.Font("Dialog", 0, 8));
        copyright.setForeground(new java.awt.Color(204, 204, 204));
        copyright.setText("(c) ESRF 2002 -");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(4, 8, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 0.1;
        add(copyright, gridBagConstraints1);
        
        progress.setStringPainted(true);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 8, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints1.weightx = 0.1;
        add(progress, gridBagConstraints1);
        
    }//GEN-END:initComponents

    public void setForeground(java.awt.Color color) {
	super.setForeground(color);
	if (copyright == null) return;
	
	copyright.setForeground(color);
	message.setForeground(color);
	title.setForeground(color);
    }


    public void setCopyright(String copyright) {
        this.copyright.setText(copyright);
    }
    
    public String getCopyright() {
        return copyright.getText();
    }
    
    public void setMessage(String message) {
        this.message.setText(message);
    }
    
    public String getMessage() {
        return message.getText();
    }
    
    public void setTitle(String title) {
        this.title.setText(title);
    }
    
    public String getTitle() {
        return title.getText();
    }
    
    public void initProgress() {
        progress.setValue(0);
    }
    
    public void progress(int i) {
        progress.setValue(i);
    }
    
    public void setMaxProgress(int i) {
        progress.setMaximum(i);
    }
    
    public void setIndeterminateProgress(boolean b) {
        progress.setIndeterminate(b);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel title;
    private javax.swing.JLabel message;
    private javax.swing.JLabel copyright;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables

}
