/*
 *  Copyright (C) :	2002,2003,2004,2005,2006,2007,2008,2009
 *			European Synchrotron Radiation Facility
 *			BP 220, Grenoble 38043
 *			FRANCE
 * 
 *  This file is part of Tango.
 * 
 *  Tango is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  Tango is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *  
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with Tango.  If not, see <http://www.gnu.org/licenses/>.
 */
 
/*
 * AppenderWindow.java
 *
 * Created on March 13, 2002, 3:40 PM
 */

package fr.esrf.tangoatk.widget.util;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author  root
 */
public class AppenderWindow extends javax.swing.JPanel {

    /** Creates new form AppenderWindow */
    public AppenderWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
          buttonGroup1 = new javax.swing.ButtonGroup();
          warningButton = new javax.swing.JRadioButton();
          infoButton = new javax.swing.JRadioButton();
          errorButton = new javax.swing.JRadioButton();
          jScrollPane2 = new javax.swing.JScrollPane();
          errorArea = new javax.swing.JTextArea();
          
          
          setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints1;
          
          warningButton.setText("warning");
          buttonGroup1.add(warningButton);
          warningButton.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  warningButtonMouseClicked(evt);
              }
          });
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
          add(warningButton, gridBagConstraints1);
          
          infoButton.setText("Info");
          buttonGroup1.add(infoButton);
          infoButton.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  infoButtonMouseClicked(evt);
              }
          });
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
          add(infoButton, gridBagConstraints1);
          
          errorButton.setText("Error");
          buttonGroup1.add(errorButton);
          errorButton.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  errorButtonMouseClicked(evt);
              }
          });
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
          gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
          add(errorButton, gridBagConstraints1);
          
          jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
          jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 400));
          jScrollPane2.setAutoscrolls(true);
          jScrollPane2.setViewportView(errorArea);
          
          gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 0.1;
        gridBagConstraints1.weighty = 0.1;
        add(jScrollPane2, gridBagConstraints1);
        
    }//GEN-END:initComponents

    protected void errorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errorButtonMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_errorButtonMouseClicked

    protected void infoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoButtonMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_infoButtonMouseClicked

    protected void warningButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warningButtonMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_warningButtonMouseClicked

    public void append(java.lang.String message) {
        errorArea.append(message);
        errorArea.append("\n");
    }    

    public void replace(java.lang.String orig, String newVal) {
	String text = errorArea.getText();
	int index = text.lastIndexOf(orig);
	if (index == -1) return;

	errorArea.replaceRange(newVal, index, text.length());
    }
    
    public void setButtonsVisible(boolean visible) {
	infoButton.setVisible(visible);
	warningButton.setVisible(visible);
	errorButton.setVisible(visible);
    }

    public boolean getButtonsVisible() {
	return infoButton.isVisible();
    }

    public void scrollToEnd() {
        Rectangle visible = errorArea.getVisibleRect();
        Rectangle bounds = errorArea.getBounds();
        visible.y = bounds.height - visible.height;
        visible.x = 0;
        errorArea.scrollRectToVisible(visible);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton warningButton;
    private javax.swing.JRadioButton infoButton;
    private javax.swing.JRadioButton errorButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea errorArea;
    // End of variables declaration//GEN-END:variables

}
