/*
 * GraphScalarViewer.java
 *
 * Created on December 3, 2001, 4:49 PM
 */

package fr.esrf.tangoatk.widget.attribute;
import java.beans.*;
import fr.esrf.tangoatk.core.*;
import fr.esrf.tangoatk.util.*;
import javax.swing.*;
/**
 *
 * @author  root
 */
public class GraphScalarViewer extends javax.swing.JFrame implements fr.esrf.tangoatk.core.INumberScalarListener, Runnable {
    AppLauncher controller;
    /** Creates new form GraphScalarViewer */
    public GraphScalarViewer() {
        initComponents();
	//	attributePropertyListWidget2.setPreferredSize(200, 300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        graphScalarViewer3 = new fr.esrf.tangoatk.widget.attribute.GraphScalarViewer();
	alarm = new fr.esrf.tangoatk.widget.attribute.AttributeAlarm();
	stringImageViewer = new fr.esrf.TangoATK.Widget.StringImageViewer();
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

  	gridBagConstraints1 = new java.awt.GridBagConstraints();
 	gridBagConstraints1.gridx = 0;
 	gridBagConstraints1.gridy = 0;
 	getContentPane().add(alarm, gridBagConstraints1);
	
  	gridBagConstraints1 = new java.awt.GridBagConstraints();
 	gridBagConstraints1.gridx = 1;
 	gridBagConstraints1.gridy = 0;
	getContentPane().add(stringImageViewer, gridBagConstraints1);

        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        getContentPane().add(graphScalarViewer3, gridBagConstraints1);
        

    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
	fr.esrf.tangoatk.core.Util.AtkTimer.getInstance().printResults();
	l.stopRefresher();
	graphScalarViewer3.stop();
	try {
	    Thread.currentThread().join(1000);		     
	} catch (Exception e) {
	    ;
	} // end of try-catch
	
	System.gc();

    }//GEN-LAST:event_exitForm

    public void setAttributeListsVisible(boolean b) {
	attributeListsVisible = b;
    }

    private boolean attributeListsVisible = true;
    fr.esrf.tangoatk.core.AttributeList l = new fr.esrf.tangoatk.core.AttributeList();
    public void run() {
	setAttributeListsVisible(false);
		try {
	    INumberScalar ns =
		(INumberScalar)l.add("eas/test-api/1/Att_sinus");
	    setModel(ns);
	//     ns = (INumberScalar)l.add("eas/test-api/1/Att_sinus1");
// 	    setModel(ns);
// 	    ns = (INumberScalar)l.add("eas/test-api/1/Att_sinus2");
// 	    setModel(ns);
// 	    ns = (INumberScalar)l.add("eas/test-api/1/Att_sinus3");
// 	    setModel(ns);
// 	    ns = (INumberScalar)l.add("eas/test-api/1/Att_sinus4");
// 	    setModel(ns);
// 	    ns = (INumberScalar)l.add("eas/test-api/1/Att_sinus5");
// 	    setModel(ns);
// 	    ANumberImage ai = (ANumberImage)l.add("MP/test/1/rd_image_short");
// 	    stringImageViewer.setModel(ai);

	    l.setRefreshInterval(90);
	    l.startRefresher();
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(this, e, "Error",
					  JOptionPane.ERROR_MESSAGE);
	    return;
	} // end of try-catch
	System.out.println("packing...");
	pack();
	System.out.println("showing...");
	show();


    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new GraphScalarViewer().run();
	//	gsv.setSize(900, 900);
    }

    public void setModel(fr.esrf.tangoatk.core.INumberScalar iNumberScalar) {
        graphScalarViewer3.setModel(iNumberScalar);
	graphScalarViewer3.setYRange(-3, 3);
	graphScalarViewer3.setXRange(0, 200);
	graphScalarViewer3.setWrap(true);
	graphScalarViewer3.setXPersistence(200);
	graphScalarViewer3.setButtons(true);
	graphScalarViewer3.start();
	graphScalarViewer3.setButtons(false);
	graphScalarViewer3.setConnected(true);
	graphScalarViewer3.setTitle(iNumberScalar.getProperty("name").getPresentation());
	alarm.setModel(iNumberScalar);
    }    

    public java.lang.String getValue() {
	return null;
    }
    
    public void setController(AppLauncher l) {
	controller = l;
    }

    public void numberScalarChange(NumberScalarEvent e) {
    }
    
    public void errorChange(ErrorEvent e) {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables

    private fr.esrf.tangoatk.widget.attribute.GraphScalarViewer graphScalarViewer3;
    private fr.esrf.tangoatk.widget.attribute.AttributeAlarm alarm;
    fr.esrf.TangoATK.Widget.StringImageViewer stringImageViewer;
    // End of variables declaration//GEN-END:variables

}
