// File:          StringImageViewer.java
// Created:       2001-11-07 15:55:09, assum
// By:            <assum@esrf.fr>
// Time-stamp:    <2002-03-12 16:38:50, assum>
// 
// $Id$
// 
// Description:       
package fr.esrf.tangoatk.widget.attribute;

import javax.swing.*;
import fr.esrf.tangoatk.core.IImageAttribute;
import fr.esrf.tangoatk.core.*;
import org.apache.log4j.Logger;
public class StringImageViewer extends JPanel
    implements fr.esrf.tangoatk.core.IImageListener {
    double value = 0;
    int currentX = 0;
    boolean full = false;
    IImageAttribute model;
    JTextField [][] textFields;
    int xIncrement = 0;
    int currentItem = 0;
    int firstItem = 0;

    static Logger log =
	Logger.getInstance(StringImageViewer.class.getName());
    
    public void setModel(IImageAttribute m) {
        model = m;
	model.addImageListener(this);
	textFields = new JTextField[model.getMaxYDimension()]
	    [model.getMaxXDimension()];

	log.debug("creating new JTextFields[" + model.getMaxYDimension() +
		  "][" + model.getMaxXDimension() + "] for " +
		  model.getName());
	    
	for (int i = 0; i < textFields.length; i++) {
	    for (int j = 0; j < textFields[i].length; j++) {
		textFields[i][j] = new JTextField();
		add(textFields[i][j]);
	    }

	}
	log.debug("Done adding textfields for " + model.getName());
	String [][] d = model.getValue();

	if (d == null || d[0] == null) return;
	log.debug("Initializing textfields for " + model.getName());
	log.debug("model.getXDimension() = " + model.getXDimension());
	log.debug("model.getYDimension() = " + model.getYDimension());
	log.debug("d.length = " + d.length);
	log.debug("d[0].length = " + d[0].length);
	log.debug("textfields.length = " + textFields.length);
	log.debug("textfields[0].length = " + textFields[0].length);
	for (int i = 0; i < d.length; i++) {
	    for (int j = 0; j < d[i].length; j++) {
		log.debug("trying model.value[" + i + "][ " + j + "]");
		
		textFields[i][j].setText(d[i][j]);
		log.debug("model.value[" + i + "][ " + j + "] = " + d[i][j]);
	    }
	}

    }

    /** Creates new customizer SimpleAttributeViewer */
    public StringImageViewer() {
        initComponents ();
	xIncrement = 5;

    }

    /** This
	method is called from within the constructor to
	* initialize the form.
	* WARNING: Do NOT modify this code. The content of this method is
	* always regenerated by the FormEditor.
	*/
    private void initComponents() {//GEN-BEGIN:initComponents
        setBackground(java.awt.Color.white);
	setSize(420, 320);
        
    }//GEN-END:initComponents

    public String [][] getValue() {
	return model.getValue();
    }

    public void errorChange(ErrorEvent e) {

    }
    
    public void imageChange(ImageEvent e) {
	String[][] v = e.getValue();
	if (v == null) return;
	for (int i = 0; i < model.getYDimension(); i++) {
	    for (int j = 0; j < model.getXDimension(); j++) {
		textFields[i][j].setText(v[i][j]);
	    }
	}
	repaint();
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables

    // End of variables declaration//GEN-END:variables

}
