/*
 * TrendOptions.java
 *
 * Created on May 14, 2002, 5:13 PM
 */

package fr.esrf.tangoatk.widget.attribute;
import javax.swing.*;
/**
 *
 * @author  root
 */
public class TrendOptions extends javax.swing.JPanel {
    Trend trend;
    /** Creates new form TrendOptions */
    public TrendOptions() {
        initComponents();
    }

    public TrendOptions(Trend t) {
	this();
	trend = t;
	xAxisLength.setText(Integer.toString(t.getXAxisLength()));
	samplingRate.setText(Double.toString(t.getSamplingRate()));
	logarithmic.setSelected(t.isLogarithmic());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            jTabbedPane1 = new javax.swing.JTabbedPane();
            general = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            logarithmic = new javax.swing.JCheckBox();
            xAxisLength = new javax.swing.JTextField();
            samplingRate = new javax.swing.JTextField();
            expert = new javax.swing.JPanel();
            
            setLayout(new java.awt.BorderLayout());
            
            setPreferredSize(new java.awt.Dimension(240, 300));
            jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
            general.setLayout(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints gridBagConstraints2;
            
            jLabel1.setText("X-axis length");
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 1;
            gridBagConstraints2.gridy = 2;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints2.insets = new java.awt.Insets(0, 3, 0, 0);
            gridBagConstraints2.anchor = java.awt.GridBagConstraints.EAST;
            general.add(jLabel1, gridBagConstraints2);
            
            jLabel2.setText("Sampling rate");
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 1;
            gridBagConstraints2.gridy = 1;
            gridBagConstraints2.insets = new java.awt.Insets(0, 3, 0, 0);
            general.add(jLabel2, gridBagConstraints2);
            
            jLabel3.setText("Logarithmic");
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 1;
            gridBagConstraints2.gridy = 0;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints2.insets = new java.awt.Insets(0, 3, 0, 0);
            general.add(jLabel3, gridBagConstraints2);
            
            logarithmic.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    logarithmicActionPerformed(evt);
                }
            });
            
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 0;
            gridBagConstraints2.anchor = java.awt.GridBagConstraints.EAST;
            general.add(logarithmic, gridBagConstraints2);
            
            xAxisLength.setColumns(10);
            xAxisLength.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            xAxisLength.setText("50");
            xAxisLength.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    xAxisLengthKeyPressed(evt);
                }
            });
            
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 2;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
            general.add(xAxisLength, gridBagConstraints2);
            
            samplingRate.setColumns(10);
            samplingRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            samplingRate.setText("1");
            samplingRate.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    samplingRateKeyPressed(evt);
                }
            });
            
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 1;
            gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
            general.add(samplingRate, gridBagConstraints2);
            
            jTabbedPane1.addTab("General", general);
          
          jTabbedPane1.addTab("Expert", expert);
          
          add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void xAxisLengthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xAxisLengthKeyPressed
        // Add your handling code here:
	if (evt.getKeyCode() == evt.VK_ENTER) {
	    try {
		trend.setXAxisLength
		    (Integer.parseInt(xAxisLength.getText()));
	    } catch (NumberFormatException e) {
		JOptionPane.showMessageDialog(this,
					      "Xaxis length should be " +
					      "an integer value",
					      "Error",
					      JOptionPane.ERROR_MESSAGE);
	    } // end of try-catch
	}
	
    }//GEN-LAST:event_xAxisLengthKeyPressed

    private void samplingRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_samplingRateKeyPressed
        // Add your handling code here:
	if (evt.getKeyCode() == evt.VK_ENTER) {
	    try {
		trend.setSamplingRate
		    (Double.parseDouble(samplingRate.getText()));
	    } catch (NumberFormatException e) {
		JOptionPane.showMessageDialog(this,
					      "sampling rate should be " +
					      "a double value",
					      "Error",
					      JOptionPane.ERROR_MESSAGE);
	    } // end of try-catch
	}
    }//GEN-LAST:event_samplingRateKeyPressed

    private void logarithmicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarithmicActionPerformed
        // Add your handling code here:
	trend.setLogarithmicScale(logarithmic.isSelected());
    }//GEN-LAST:event_logarithmicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel general;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox logarithmic;
    private javax.swing.JTextField xAxisLength;
    private javax.swing.JTextField samplingRate;
    private javax.swing.JPanel expert;
    // End of variables declaration//GEN-END:variables

}
