include ../../../../.make-include

ALL=$(TARGET)/BaseDesktopManager.class \
    $(TARGET)/BaseDesktopPane.class \
    $(TARGET)/BaseInternalFrame.class \
    $(TARGET)/BaseMenuItem.class \
    $(TARGET)/BaseRadioButtonMenuItem.class \
    $(TARGET)/BaseToggleButton.class \
    $(TARGET)/ConstructWindowMenu.class \
    $(TARGET)/DesktopConstants.class \
    $(TARGET)/DesktopListener.class \
    $(TARGET)/DesktopMediator.class \
    $(TARGET)/DesktopMenu.class \
    $(TARGET)/DesktopResizableToolBar.class \
    $(TARGET)/EmptyDesktopIconUI.class \
    $(TARGET)/FrameAccessorInterface.class \
    $(TARGET)/FramePositioning.class \
    $(TARGET)/DesktopScrollPane.class \
    $(TARGET)/JScrollableDesktopPane.class \
    $(TARGET)/ResizableToolBar.class \

all: $(ALL)
	$(J)

clean: class-clean