include ../../../../../../../.make-include


ALL =   $(TARGET)/DomainNode.class \
        $(TARGET)/FamilyNode.class \
        $(TARGET)/MemberNode.class \
        $(TARGET)/DeviceTreeCellRenderer.class \

all: $(ALL)
	$(J)