/*
 * IconNumberScalarViewer.java
 *
 * Created on March 19, 2002, 5:49 PM
 */

package fr.esrf.tangoatk.widget.attribute;
import javax.swing.*;
import java.awt.Dimension;
/**
 *
 * @author  root
 */
public class IconNumberScalarViewer extends javax.swing.JPanel implements fr.esrf.tangoatk.core.INumberScalarListener {

    /** Creates new form IconNumberScalarViewer */
    public IconNumberScalarViewer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        icon = new javax.swing.JLabel();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 0.1;
        gridBagConstraints1.weighty = 0.1;
        add(icon, gridBagConstraints1);
        
    }//GEN-END:initComponents

    public void errorChange(fr.esrf.tangoatk.core.ErrorEvent errorEvent) {
    }    

    public void stateChange(fr.esrf.tangoatk.core.AttributeStateEvent evt) {

    }

    public void numberScalarChange(fr.esrf.tangoatk.core.NumberScalarEvent numberScalarEvent) {
        int val = (int)numberScalarEvent.getValue();
        if (val >= 0 && val < icons.length) {
            icon.setIcon(icons[val]);
        }
    }    

    public void setModel(fr.esrf.tangoatk.core.INumberScalar model) {
        if (model != null) {
            model.removeNumberScalarListener(this);
        }
        
        this.model = model;
       
        model.addNumberScalarListener(this);
    }
    
    public fr.esrf.tangoatk.core.INumberScalar getModel() {
        return model;
    }
    
    public void setIcons(javax.swing.Icon [] icons) {
        this.icons = icons;
    }
    
    public javax.swing.Icon[] getIcons() {
        return icons;
    }

    public void setPreferredSize(Dimension dimension) {
	super.setPreferredSize(dimension);
	icon.setPreferredSize(dimension);
    }

    public Dimension getPreferredSize() {
	return super.getPreferredSize();
    }
    
    public static void main (String[] args) throws Exception {
	Icon [] icons = new Icon[2];
	 fr.esrf.tangoatk.core.AttributeList list =
	     new fr.esrf.tangoatk.core.AttributeList();
	 fr.esrf.tangoatk.core.INumberScalar i =
	     (fr.esrf.tangoatk.core.INumberScalar)list.add("eas/test-api/1/Att_eas");
	 IconNumberScalarViewer ins = new IconNumberScalarViewer();
	 icons[0] = new ImageIcon(ins.getClass().getResource("/fr/esrf/TangoATK/Widget/Attribute/NumberScalarViewer.gif"));
	icons[1] = new ImageIcon(ins.getClass().getResource("/fr/esrf/TangoATK/Widget/Attribute/JChartAdapter.gif"));
	ins.setPreferredSize(new Dimension(100, 100));
	 ins.setModel(i);
	 ins.setIcons(icons);
	 list.startRefresher();
	 JFrame f = new JFrame();
	 f.getContentPane().add(ins);
	 f.pack();
         f.setVisible(true);
	 
    } // end of main ()
    
    private javax.swing.Icon [] icons;
    private fr.esrf.tangoatk.core.INumberScalar model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    // End of variables declaration//GEN-END:variables

    
}
